In [1]:
import numpy as np

In [2]:
escalar = 5.679
vector = np.array([3,4,5,6])
matriz = np.array([[1,2],[3,4],[5,6]])
tensor = np.array([
    [[1,2,3,30],[4,5,6,31],[7,8,9,32]],
    [[11,12,13,33],[14,15,16,34],[17,18,19,35]],
    [[11,12,13,36],[14,15,16,37],[17,18,19,38]],
])

In [3]:
escalar_t = escalar.T

AttributeError: 'float' object has no attribute 'T'

In [5]:
vector_t = vector.T
print(vector_t)

[3 4 5 6]


In [8]:
matriz_t = matriz.T
print(matriz_t)

[[1 3 5]
 [2 4 6]]


In [10]:
print(matriz.shape)

(3, 2)


In [11]:
print(matriz_t.shape)

(2, 3)


In [12]:
tensor_t = tensor.T
print(tensor_t)

[[[ 1 11 11]
  [ 4 14 14]
  [ 7 17 17]]

 [[ 2 12 12]
  [ 5 15 15]
  [ 8 18 18]]

 [[ 3 13 13]
  [ 6 16 16]
  [ 9 19 19]]

 [[30 33 36]
  [31 34 37]
  [32 35 38]]]


In [13]:
# (Mt)t = M La transpuesta de una matriz transpuesta, nos devuelve la misma matriz.

matriz_t_t = matriz_t.T
print(matriz_t_t)

[[1 2]
 [3 4]
 [5 6]]


In [14]:
# Suma de matrices de mismo tamaño

A = matriz
B = matriz_t

In [16]:
# A+B nos devolver;á error porque no tienen la misma dimensi;ón, 2x3 y 3x2
C = A+B

ValueError: operands could not be broadcast together with shapes (3,2) (2,3) 

In [17]:
A = np.array([[1,2],[3,4],[5,6]])
B = np.array([[6,5],[4,3],[2,1]])
C = A+B
print(A)
print(B)
print(C)

[[1 2]
 [3 4]
 [5 6]]
[[6 5]
 [4 3]
 [2 1]]
[[7 7]
 [7 7]
 [7 7]]


In [19]:
# Sumamos la matriz con el escalar, esto le suma cada escalar a cada elemento de la matriz.

D = matriz + escalar
print(D)

[[ 6.679  7.679]
 [ 8.679  9.679]
 [10.679 11.679]]
