In [1]:
import numpy as np

In [4]:
escalar = 5.769
vector = np.array([3,4,5])
matriz = np.array([[1,2],[3,4],[5,6]])

In [5]:
A = vector + matriz

ValueError: operands could not be broadcast together with shapes (3,) (3,2) 

In [9]:
A = matriz.T + vector
print(A)

[[ 4  7 10]
 [ 5  8 11]]


In [10]:
C = matriz + 42
print(C)

[[43 44]
 [45 46]
 [47 48]]


In [13]:
matriz5 = np.array([
    [1,2,3,4,5], 
    [6,7,8,9,10], 
    [11,12,13,14,15],
    [16,17,18,19,20],
    [20,21,22,23,24],
])
vector5 = np.array([1,1,1,1,1])

In [15]:
D = matriz5 + vector5
print(D)

[[ 2  3  4  5  6]
 [ 7  8  9 10 11]
 [12 13 14 15 16]
 [17 18 19 20 21]
 [21 22 23 24 25]]
