In [1]:
import numpy as np

In [7]:
escalar = 5.679
vector = np.array([2,3])
matriz = np.array([[1,2],[3,4],[5,6]])

In [8]:
A = matriz * vector

In [9]:
B = matriz.dot(vector)

In [10]:
print(A)

[[ 2  6]
 [ 6 12]
 [10 18]]


In [11]:
print(B)

[ 8 18 28]


In [12]:
B = matriz.dot(vector)
C = np.dot(matriz, vector)

In [16]:
print(B)
print(C)

[ 8 18 28]
[ 8 18 28]


In [20]:
# reto vector.dot(matriz)

vector = np.array([1,2,3])
matriz = np.array([[1,2],[3,4],[5,6]])

D = vector.dot(matriz)

print(D)

[22 28]
