In [1]:
import numpy as np

In [2]:
A = np.array([[2,3],[5,7],[11,13]])
B = np.array([[1,3],[2,1]])
C = np.array([[3,1],[4,2]])

In [5]:
# Asociativa Ax(BxC) = (AxB)xC

A_BC = A.dot(B.dot(C))
print(A_BC)

[[ 60  26]
 [145  63]
 [295 129]]


In [6]:
AB_C = A.dot(B).dot(C)
print(AB_C)

[[ 60  26]
 [145  63]
 [295 129]]


In [8]:
# Distritutiva Ax(B+C) = (AxB + AxC)

D = A.dot(B+C)
E = A.dot(B) + A.dot(C)
print(D)
print(E)

[[ 26  17]
 [ 62  41]
 [122  83]]
[[ 26  17]
 [ 62  41]
 [122  83]]


In [9]:
# forma para verificar coincidencia entre matrices, elemento a elemento

print(D==E)

[[ True  True]
 [ True  True]
 [ True  True]]


In [10]:
# Conmutativa BxC = CxB

F = B.dot(C)

In [11]:
G = C.dot(B)

In [12]:
print(F==G)

[[False False]
 [False False]]


In [13]:
print(F)

[[15  7]
 [10  4]]


In [14]:
print(G)

[[ 5 10]
 [ 8 14]]


In [ ]:
# multiplicaci;ón de vectores si es conmutativa

v1 = np.array([[2],[7]])
v2 = np.array([[3],[]])