In [1]:
import numpy as np

In [2]:
A = np.array([[2,3],[5,7],[11,13]])
B = np.array([[1,3],[2,1]])

In [4]:
print(A)
print(B)

[[ 2  3]
 [ 5  7]
 [11 13]]
[[1 3]
 [2 1]]


In [5]:
AB_t = A.dot(B).T

In [6]:
B_t_A_t = B.T.dot(A.T)

In [7]:
print(AB_t)
print(B_t_A_t)

[[ 8 19 37]
 [ 9 22 46]]
[[ 8 19 37]
 [ 9 22 46]]


In [8]:
print(AB_t==B_t_A_t)

[[ True  True  True]
 [ True  True  True]]
