In [1]:
import numpy as np

In [8]:
identidad = np.eye(4) #definimos matriz con valores floats (decimales)

In [3]:
print(identidad)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [5]:
vector = np.array([[2],[3],[5],[7]])

In [6]:
print(vector)

[[2]
 [3]
 [5]
 [7]]


In [9]:
print(identidad.dot(vector)) #prod int entre matriz identidad y vector devuelve el mismo vector

[[2.]
 [3.]
 [5.]
 [7.]]


In [11]:
# MATRIZ INVERSA

A = np.array([[1,0,1],[0,1,1],[-1,1,1]]) #creamos una matriz
print(A)

[[ 1  0  1]
 [ 0  1  1]
 [-1  1  1]]


In [13]:
#calculamos inversa de A

inversa_A = np.linalg.inv(A)
print(inversa_A)

[[ 0.  1. -1.]
 [-1.  2. -1.]
 [ 1. -1.  1.]]


In [15]:
#verificamso A.A-1 = Id
# para este resultado nos arrojar;á una matriz identidad

print(A.dot(inversa_A))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [16]:
# cuando no nos arroja una matriz identidad (no existe la inversa), nos arroja una matriz singular

singular = np.array([[1,1],[1,1]])
print(singular)

[[1 1]
 [1 1]]


In [18]:
print(np.linalg.inv(singular))

LinAlgError: Singular matrix