In [1]:
import numpy as np

In [2]:
#decimos a numpy que utilize 0 cuadno valor decimal sea muy pequeño.
np.set_printoptions(suppress=True)

In [3]:
A = np.array([[3,1],[2,1]])
print(A)

[[3 1]
 [2 1]]


In [4]:
B = np.array([[1],[1]])
print(B)

[[1]
 [1]]


In [6]:
inversa_A = np.linalg.inv(A)
print(inversa_A)

[[ 1. -1.]
 [-2.  3.]]


In [8]:
#hallamos nuestra x = B.A-1
x = inversa_A.dot(B)
print(x)

[[0.]
 [1.]]


In [9]:
#verificamos que efectivamente x es la soluci;ón a nuestro problema

print(A.dot(x))

[[1.]
 [1.]]


In [10]:
#si tenemos la ecuaci;ón igualada a otros coefecientes nos sirve la misma inversa
#3x+y=3
#2x+y=7

sol_2 = inversa_A.dot(np.array([[3],[7]]))
print(sol_2)

[[-4.]
 [15.]]


In [11]:
print(A.dot(sol_2))

[[3.]
 [7.]]
