In [1]:
import numpy as np

In [3]:
vector = np.array([1,2,3,4,5]) #creamos vector

matriz = np.diag(vector) #creamos matriz diagonal con vector anterior

print(matriz)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [8]:
print(matriz[0:4,0:3]) # imprimimos matriz con ls cuatro primeras filas y las tres primeras columnas

# con esto se verifica que esta matriz es diagonal pero no es cuadrada

[[1 0 0]
 [0 2 0]
 [0 0 3]
 [0 0 0]]


In [5]:
print(matriz[0:3,0:4])  # imprimimos matriz con las tres primeras filas y las cuatro primeras columnas

# con esto se verifica que esta matriz es diagonal 

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]]


In [10]:
A = np.diag([2,3,4,5]) #creamos matriz diagonal con 2,3,4,5
print(A)

[[2 0 0 0]
 [0 3 0 0]
 [0 0 4 0]
 [0 0 0 5]]


In [14]:
v1 = np.array([[1,1,1,1]]) #creamos vector vertical

print(v1)

print(A.dot(v1.T))

[[1 1 1 1]]
[[2]
 [3]
 [4]
 [5]]


In [18]:
A_inv = np.diag([1/2, 1/3, 1/4, 1/5]) # calculamos la inversa de matriz A colocando como dividendo cada valor de la diagonal de la matriz
print(A_inv)

[[0.5        0.         0.         0.        ]
 [0.         0.33333333 0.         0.        ]
 [0.         0.         0.25       0.        ]
 [0.         0.         0.         0.2       ]]


In [19]:
identidad = A.dot(A_inv) # calculamos la identidad de matriz A con prod interno entre matriz A y la inversa de matriz A

print(identidad)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [20]:
A_inv = np.linalg.inv(A) # calculamos directamente inversa de matriz A para comparar

print(A_inv)

[[0.5        0.         0.         0.        ]
 [0.         0.33333333 0.         0.        ]
 [0.         0.         0.25       0.        ]
 [0.         0.         0.         0.2       ]]


In [22]:
print(A.T) # comprobamos que matriz A es sim;étrica calculando su traspuesta

[[2 0 0 0]
 [0 3 0 0]
 [0 0 4 0]
 [0 0 0 5]]


In [23]:
print(A)

[[2 0 0 0]
 [0 3 0 0]
 [0 0 4 0]
 [0 0 0 5]]


In [24]:
# para matrices en general, veriricar si es simetrica es un poco mas complicado

simetrica = np.array([
    [1,2,3],
    [2,-1,7],
    [3,7,11]
])

print(simetrica)

[[ 1  2  3]
 [ 2 -1  7]
 [ 3  7 11]]


In [26]:
print(simetrica.T) # no solamente las matrices diagonales pueden ser simetricas

[[ 1  2  3]
 [ 2 -1  7]
 [ 3  7 11]]
