In [1]:
import numpy as np

In [4]:
matriz = np.array([
    [1,0,0],
    [0,1,0],
    [0,0,1]
])

print(matriz)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [5]:
# Verificaremos si matriz es ortogonal, comporbando que sus columnas y filas son mutuamente ortonormales, 
# para eso necesitamos comprobar que son ortogonales y con norma 1

#Necesitaremos realizar 3 verificaciones por columnas porque la matriz es 3x3
# v1 ortogonal v2
# v1 ortogonal v3
# v2 ortogonal v3

In [6]:
# v1 ortogonal v2 columnas
#seleccionamos la primer columna de la matriz [:,0] hacemos producto interno con la segunda columna de la matriz [:,1]

print(matriz[:,0].dot(matriz[:,1])) # si resultado prod inter es 0, son ortogonales

0


In [8]:
# v1 ortogonal v3 columnas
#seleccionamos la primer columna de la matriz [:,0] hacemos producto interno con la tercera columna de la matriz [:,2]

print(matriz[:,0].dot(matriz[:,2])) # si resultado prod inter es 0, son ortogonales

0


In [13]:
# v2 ortogonal v3 columnas
#seleccionamos la segunda columna de la matriz [:,1] hacemos producto interno con la tercera columna de la matriz [:,2]

print(matriz[:,1].dot(matriz[:,2])) # si resultado prod inter es 0, son ortogonales

0


In [12]:
# validamos las normas de cada vector sean igual a 1 

print(np.linalg.norm(matriz[:,0]))
print(np.linalg.norm(matriz[:,1]))
print(np.linalg.norm(matriz[:,2]))

1.0
1.0
1.0


In [14]:
#Necesitaremos realizar 3 verificaciones por filas porque la matriz es 3x3
# v1 ortogonal v2
# v1 ortogonal v3
# v2 ortogonal v3

In [16]:
# v1 ortogonal v2 fiilas
#seleccionamos la primer fila de la matriz [0,:] hacemos producto interno con la segunda fila de la matriz [1,:]

print(matriz[0,:].dot(matriz[1,:])) # si resultado prod inter es 0, son ortogonales

0


In [19]:
# v1 ortogonal v3 fiilas
#seleccionamos la primer fila de la matriz [0,:] hacemos producto interno con la tercera fila de la matriz [2,:]

print(matriz[0,:].dot(matriz[2,:])) # si resultado prod inter es 0, son ortogonales

0


In [20]:
# v2 ortogonal v3 fiilas
#seleccionamos la segunda fila de la matriz [1,:] hacemos producto interno con la tercera fila de la matriz [2,:]

print(matriz[1,:].dot(matriz[2,:])) # si resultado prod inter es 0, son ortogonales

0


In [21]:
# validamos las normas de cada vector de filas sean igual a 1 

print(np.linalg.norm(matriz[0,:]))
print(np.linalg.norm(matriz[1,:]))
print(np.linalg.norm(matriz[2,:]))

1.0
1.0
1.0


In [22]:
# Vamos a generar matrices ortogonales:

A = np.array([[np.cos(100), -np.sin(100)], # defiinimos una matriz mediante funciones coseno y seno
              [np.sin(100), np.cos(100)]
             ])

print(A)

[[ 0.86231887  0.50636564]
 [-0.50636564  0.86231887]]


In [24]:
# calculamos las normas por filas y columnas de la matriz

print(np.linalg.norm(A[0,:]))
print(np.linalg.norm(A[1,:]))
print(np.linalg.norm(A[:,0]))
print(np.linalg.norm(A[:,1]))

0.9999999999999999
0.9999999999999999
0.9999999999999999
0.9999999999999999


In [27]:
# calculamos angulo 90 entre vectores, mediante producto interno entre filas y entre columnas

print(A[0,:].dot(A[1,:]))
print(A[:,0].dot(A[:,1]))

# Resultado arroja que son ortogonales ;ángulo 90°

0.0
0.0


In [30]:
# Calcularemos producto inteno de la trspuesta de la matriz y la matriz, y viceversa.

A_t = A.T
print(A_t.dot(A))
print(A.dot(A_t))

# El resultado arroja la matriz identidad de la matriz A

[[1. 0.]
 [0. 1.]]
[[1. 0.]
 [0. 1.]]


In [31]:
A_inv = np.linalg.inv(A)
print(A_inv)

[[ 0.86231887 -0.50636564]
 [ 0.50636564  0.86231887]]


In [32]:
print(A_t)

[[ 0.86231887 -0.50636564]
 [ 0.50636564  0.86231887]]


In [33]:
print(1/A_t.dot(A))

# arrojar;á dos n;úmeros infinitos en la matriz resultante "inf"

[[ 1. inf]
 [inf  1.]]


C:\Users\jam\anaconda3\envs\Platzi-FundamentosAL\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.
